# Generated by Django 5.1.1 on 2024-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CURDAPP', '0002_curdpro_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curdpro',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
